site_name: Docs LINO-PIMO

site_url: ""

use_directory_urls: false

plugins: []

nav:
    - Home: index.md
    - Tutoriel: tuto.md
    - Docs: docs.md
    - Commandes: commands.md
    - Exemples: example.md
    - License: license.md

theme: readthedocs

copyright: Copyright (C) 2022 CGI France - GNU License GPLv3
