name: Documentation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Build devcontainer
        run: docker build . --file .devcontainer/Dockerfile
      
      - name: Generate docs
        run: mkdocs serve 
        

     
